# Generated by Django 4.2.6 on 2024-03-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledata',
            old_name='is_client',
            new_name='has_more_profile',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='is_organizer',
        ),
    ]
