# Generated by Django 4.2.6 on 2024-03-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='referenceId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
