# Generated by Django 4.2.6 on 2024-03-24 14:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_package_event_referenceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('deleted_status', models.BooleanField(default=False)),
                ('doneAt', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.CharField(editable=False, max_length=255)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_type',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='eventCategory',
            field=models.CharField(choices=[('One-Day', 'One-Day'), ('Series', 'Series')], default='One-Day', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.eventtype'),
            preserve_default=False,
        ),
    ]
