# Generated by Django 4.2.6 on 2024-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventtype_event_eventcategory_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='will_be_there',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
